### ISSUE TITLE
About ctr_thred

### ISSUE THREAD

**Issue by whyandbecause** [liyi01827/noisy-contrastive#2]
Hi, thank you for you excellent work. I tried to train your code on my dataset,  i found commands in run.sh all with a argument ctr_thred,  but it can't be found in mian.py. Can you give me some advice?

**Comment by whyandbecause** [comment]
I re-trained your work on CIFAR10 by noise ratio=20% without ctr_thred argument, after 550 epochs, I got final result like:

**dataset: cifar10	 noise_type: sym	 noise_ratio: 0.2 	lamb: 50.0	 tau: 0.8	 type: ce 	 seed: 123 	 best_acc: 91.24802215189874	last_acc: 90.03164556962025**

this result is far from your result( 93.05±0.32) in paper, how can i fix this probelm. Thanks for your reply.

**Comment by liyi01827** [comment]
Hi, thank you for your comments. The argument "ctr_thred" is "tau" in the main.py. I've fixed the typo. 

For CIFAR10 with 20%SYM, when you change tau to 0.4, you should get a higher ACC.

**Comment by whyandbecause** [comment]
It works for me, thank you for your reply!
